
server:
  port: 8888


spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Mac SSD/Usuários/cassio/Documentos/Servidor/microservice-repo
          